#!/bin/bash
echo "--$(date '+%F-%T')---------" >> check
echo "fecha,usuario,readme,repo,usuario">> check
cat usuarios.txt | while read line || [[ -n $line ]];
do
	echo "https://github.com/$line/$line"
	user_s=$(curl -s -o /dev/null -I -w "%{http_code}" "https://github.com/$line")
	repo_s=$(curl -s -o /dev/null -I -w "%{http_code}" "https://github.com/$line/$line")
	status=$(curl -s -o /dev/null -I -w "%{http_code}" "https://raw.githubusercontent.com/$line/$line/main/README.md")
	
	echo $(date '+%F-%T'),$line,$status,$repo_s,$user_s >> check
    if test $status -eq "200"
	then
		echo ">>>>OK $line"
		gh repo fork --clone $line/$line
		cd $line
		 echo "![Badge](https://bit.ly/icom-badge)" >> README.md
		 git add README.md
		 git commit -m "Agregado del badge de la carrera al perfil."
		 git push
		 gh pr create --title "Agregado automático del badge" --body "Este es un pull request automático para agregar el badge a su perfil en GitHub" 
		cd ..
		echo "Estamos en: $(pwd)"
		echo "gh repo delete martinvilu/$line --confirm" >> cleanup
	else
		echo $line >> reintento
	fi
	
done
echo "--$(date '+%F-%T')---------" >> check
